---
parent_directory: "/opt"

dhus_version: "3.0.8-3"

admin_username: "dhr"
admin_username_password: "USE_ANSIBLE_VAULT_PASSWORD"
admin_email: "YOUR_ADMIN_EMAIL"
admin_email_password: "USE_ANSIBLE_VAULT_PASSWORD"

# we are using network shares for those paths
log_path: "YOUR_LOG_PATH"
db_path: "YOUR_DB_PATH"
db_dumps_path: "YOUR_DB_DUMPS_PATH"
storage_path: "YOUR_STORAGE_PATH"

products:
  - name: "s1"
    solr_path: "{{ db_path }}/s1-solr"
    postgresql_data_dir: "{{ db_path }}/s1-psql"
    postgresql_dump_folder: "{{ db_dumps_path }}/s1"
    log_path: "{{ log_path }}/s1-logs"
    synchronizer:
      - id: 1
        label: "s1_not_slc"
        url: "DHR_URL"
        login: "DHR_LOGIN"
        password: "DHR_ANSIBLE_VAULT_PASSWORD"
        active: "true"
        page_size: "10"
        remoteIncoming: ""
        copyProduct: "true"
        filter: "startswith(Name,'S1') and not substringof('SLC',Name)"
        skipOnError: "true"
        syncOfflineProducts: "false"
      - id: 2
        label: "s1_slc"
        url: "DHR_URL"
        login: "DHR_LOGIN"
        password: "DHR_ANSIBLE_VAULT_PASSWORD"
        active: "true"
        page_size: "10"
        remoteIncoming: ""
        copyProduct: "true"
        filter: "startswith(Name,'S1') and substringof('SLC',Name)"
        skipOnError: "true"
        syncOfflineProducts: "false"
    datastore:
      - id: 1
        storage_name: "s1storage"
        storage_path: "{{ storage_path }}/s1-incoming"
        restriction: "none"
        maximumSize: "50000000000000"
        autoEviction: "false"
  - name: "s2a-l1c"
    solr_path: "{{ db_path }}/s2a-l1c-solr"
    postgresql_data_dir: "{{ db_path }}/s2a-l1c-psql"
    postgresql_dump_folder: "{{ db_dumps_path }}/s2a-l1c"
    log_path: "{{ log_path }}/s2a-l1c-logs"
    synchronizer:
      - id: 1
        label: "s2a-l1c"
        url: "DHR_URL"
        login: "DHR_LOGIN"
        password: "DHR_ANSIBLE_VAULT_PASSWORD"
        active: "true"
        page_size: "10"
        remoteIncoming: ""
        copyProduct: "true"
        filter: "startswith(Name,'S2A_MSIL1C')"
        skipOnError: "true"
        syncOfflineProducts: "false"
    datastore:
      - id: 1
        storage_name: "s2a-l1cstorage"
        storage_path: "{{ storage_path }}/s2a-l1c-incoming"
        restriction: "none"
        maximumSize: "50000000000000"
        autoEviction: "false"
  - name: "s2b-l1c"
    solr_path: "{{ db_path }}/s2b-l1c-solr"
    postgresql_data_dir: "{{ db_path }}/s2b-l1c-psql"
    postgresql_dump_folder: "{{ db_dumps_path }}/s2b-l1c"
    log_path: "{{ log_path }}/s2b-l1c-logs"
    synchronizer:
      - id: 1
        label: "s2b-l1c"
        url: "DHR_URL"
        login: "DHR_LOGIN"
        password: "DHR_ANSIBLE_VAULT_PASSWORD"
        active: "true"
        page_size: "10"
        remoteIncoming: ""
        copyProduct: "true"
        filter: "startswith(Name,'S2B_MSIL1C')"
        skipOnError: "true"
        syncOfflineProducts: "false"
    datastore:
      - id: 1
        storage_name: "s2b-l1cstorage"
        storage_path: "{{ storage_path }}/s2b-l1c-incoming"
        restriction: "none"
        maximumSize: "50000000000000"
        autoEviction: "false"
  - name: "s2-l2a"
    solr_path: "{{ db_path }}/s2-l2a-solr"
    postgresql_data_dir: "{{ db_path }}/s2-l2a-psql"
    postgresql_dump_folder: "{{ db_dumps_path }}/s2-l2a"
    log_path: "{{ log_path }}/s2-l2a-logs"
    synchronizer:
      - id: 1
        label: "s2a-l2a"
        url: "DHR_URL"
        login: "DHR_LOGIN"
        password: "DHR_ANSIBLE_VAULT_PASSWORD"
        active: "true"
        page_size: "10"
        remoteIncoming: ""
        copyProduct: "true"
        filter: "startswith(Name,'S2A') and substringof('MSIL2A',Name)"
        skipOnError: "true"
        syncOfflineProducts: "false"
      - id: 2
        label: "s2b-l2a"
        url: "DHR_URL"
        login: "DHR_LOGIN"
        password: "DHR_ANSIBLE_VAULT_PASSWORD"
        active: "true"
        page_size: "10"
        remoteIncoming: ""
        copyProduct: "true"
        filter: "startswith(Name,'S2B') and substringof('MSIL2A',Name)"
        skipOnError: "true"
        syncOfflineProducts: "false"
    datastore:
      - id: 1
        storage_name: "s2-l2astorage"
        storage_path: "{{ storage_path }}/s2-l2a-incoming"
        restriction: "none"
        maximumSize: "50000000000000"
        autoEviction: "false"
  - name: "s3"
    solr_path: "{{ db_path }}/s3-solr"
    postgresql_data_dir: "{{ db_path }}/s3-psql"
    postgresql_dump_folder: "{{ db_dumps_path }}/s3"
    log_path: "{{ log_path }}/s3-logs"
    synchronizer:
      - id: 1
        label: "s3"
        url: "DHR_URL"
        login: "DHR_LOGIN"
        password: "DHR_ANSIBLE_VAULT_PASSWORD"
        active: "true"
        page_size: "10"
        remoteIncoming: ""
        copyProduct: "true"
        filter: "startswith(Name,'S3')"
        skipOnError: "true"
        syncOfflineProducts: "false"
    datastore:
      - id: 1
        storage_name: "s3storage"
        storage_path: "{{ storage_path }}/s3-incoming"
        restriction: "none"
        maximumSize: "50000000000000"
        autoEviction: "false"
  - name: "s5"
    solr_path: "{{ db_path }}/s5-solr"
    postgresql_data_dir: "{{ db_path }}/s5-psql"
    postgresql_dump_folder: "{{ db_dumps_path }}/s5"
    log_path: "{{ log_path }}/s5-logs"
    synchronizer:
      - id: 1
        label: "s5"
        url: "DHR_URL"
        login: "DHR_LOGIN"
        password: "DHR_ANSIBLE_VAULT_PASSWORD"
        active: "true"
        page_size: "10"
        remoteIncoming: ""
        copyProduct: "true"
        filter: "startswith(Name,'S5') and not substringof('RPRO',Name)"
        skipOnError: "true"
        syncOfflineProducts: "false"
    datastore:
      - id: 1
        storage_name: "s5storage"
        storage_path: "{{ storage_path }}/s5-incoming"
        restriction: "none"
        maximumSize: "50000000000000"
        autoEviction: "false"
  - name: "dhs"
    solr_path: "{{ db_path }}/dhs-solr"
    postgresql_data_dir: "{{ db_path }}/dhs-psql"
    postgresql_dump_folder: "{{ db_dumps_path }}/dhs"
    log_path: "{{ log_path }}/dhs-logs"
    synchronizer:
      - id: 1
        label: "s1"
        url: "YOUR_S1_BACKEND_URL"
        login: "{{ admin_username }}"
        password: "{{ admin_username_password }}"
        active: "true"
        page_size: "100"
        remoteIncoming: "{{ storage_path }}/s1-incoming"
        copyProduct: "false"
        filter: ""
        skipOnError: "true"
        syncOfflineProducts: ""
      - id: 2
        label: "s2a-l1c"
        url: "YOUR_S2A_L1C_BACKEND_URL"
        login: "{{ admin_username }}"
        password: "{{ admin_username_password }}"
        active: "true"
        page_size: "100"
        remoteIncoming: "{{ storage_path }}/s2a-l1c-incoming"
        copyProduct: "false"
        filter: ""
        skipOnError: "true"
        syncOfflineProducts: ""
      - id: 3
        label: "s2b-l1c"
        url: "YOUR_S2B_L1C_BACKEND_URL"
        login: "{{ admin_username }}"
        password: "{{ admin_username_password }}"
        active: "true"
        page_size: "100"
        remoteIncoming: "{{ storage_path }}/s2b-l1c-incoming"
        copyProduct: "false"
        filter: ""
        skipOnError: "true"
        syncOfflineProducts: ""
      - id: 4
        label: "s2-l2a"
        url: "YOUR_S2_L2A_BACKEND_URL"
        login: "{{ admin_username }}"
        password: "{{ admin_username_password }}"
        active: "true"
        page_size: "100"
        remoteIncoming: "{{ storage_path }}/s2-l2a-incoming"
        copyProduct: "false"
        filter: ""
        skipOnError: "true"
        syncOfflineProducts: ""
      - id: 5
        label: "s3"
        url: "YOUR_S3_BACKEND_URL"
        login: "{{ admin_username }}"
        password: "{{ admin_username_password }}"
        active: "true"
        page_size: "100"
        remoteIncoming: "{{ storage_path }}/s3-incoming"
        copyProduct: "false"
        filter: ""
        skipOnError: "true"
        syncOfflineProducts: ""
      - id: 6
        label: "s5"
        url: "YOUR_S5_BACKEND_URL"
        login: "{{ admin_username }}"
        password: "{{ admin_username_password }}"
        active: "true"
        page_size: "100"
        remoteIncoming: "{{ storage_path }}/s5-incoming"
        copyProduct: "false"
        filter: ""
        skipOnError: "true"
        syncOfflineProducts: ""
    datastore:
      - id: 1
        storage_name: "s1storage"
        storage_path: "{{ storage_path }}/s1-incoming"
        restriction: "referencesOnly"
        maximumSize: ""
        autoEviction: ""
      - id: 2
        storage_name: "s2a-l1cstorage"
        storage_path: "{{ storage_path }}/s2a-l1c-incoming"
        restriction: "referencesOnly"
        maximumSize: ""
        autoEviction: ""
      - id: 3
        storage_name: "s2b-l1cstorage"
        storage_path: "{{ storage_path }}/s2b-l1c-incoming"
        restriction: "referencesOnly"
        maximumSize: ""
        autoEviction: ""
      - id: 4
        storage_name: "s2-l2astorage"
        storage_path: "{{ storage_path }}/s2-l2a-incoming"
        restriction: "referencesOnly"
        maximumSize: ""
        autoEviction: ""
      - id: 5
        storage_name: "s3storage"
        storage_path: "{{ storage_path }}/s3-incoming"
        restriction: "referencesOnly"
        maximumSize: ""
        autoEviction: ""
      - id: 6
        storage_name: "s5storage"
        storage_path: "{{ storage_path }}/s5-incoming"
        restriction: "referencesOnly"
        maximumSize: ""
        autoEviction: ""
  - name: "dhr"
    solr_path: "{{ db_path }}/dhr-solr"
    postgresql_data_dir: "{{ db_path }}/dhr-psql"
    postgresql_dump_folder: "{{ db_dumps_path }}/dhr"
    log_path: "{{ log_path }}/dhr-logs"
    synchronizer:
      - id: 1
        label: "s1"
        url: "YOUR_S1_BACKEND_URL"
        login: "{{ admin_username }}"
        password: "{{ admin_username_password }}"
        active: "true"
        page_size: "100"
        remoteIncoming: "{{ storage_path }}/s1-incoming"
        copyProduct: "false"
        filter: ""
        skipOnError: "true"
        syncOfflineProducts: ""
      - id: 2
        label: "s2a-l1c"
        url: "YOUR_S2A_L1C_BACKEND_URL"
        login: "{{ admin_username }}"
        password: "{{ admin_username_password }}"
        active: "true"
        page_size: "100"
        remoteIncoming: "{{ storage_path }}/s2a-l1c-incoming"
        copyProduct: "false"
        filter: ""
        skipOnError: "true"
        syncOfflineProducts: ""
      - id: 3
        label: "s2b-l1c"
        url: "YOUR_S2B_L1C_BACKEND_URL"
        login: "{{ admin_username }}"
        password: "{{ admin_username_password }}"
        active: "true"
        page_size: "100"
        remoteIncoming: "{{ storage_path }}/s2b-l1c-incoming"
        copyProduct: "false"
        filter: ""
        skipOnError: "true"
        syncOfflineProducts: ""
      - id: 4
        label: "s2-l2a"
        url: "YOUR_S2_L2A_BACKEND_URL"
        login: "{{ admin_username }}"
        password: "{{ admin_username_password }}"
        active: "true"
        page_size: "100"
        remoteIncoming: "{{ storage_path }}/s2-l2a-incoming"
        copyProduct: "false"
        filter: ""
        skipOnError: "true"
        syncOfflineProducts: ""
      - id: 5
        label: "s3"
        url: "YOUR_S3_BACKEND_URL"
        login: "{{ admin_username }}"
        password: "{{ admin_username_password }}"
        active: "true"
        page_size: "100"
        remoteIncoming: "{{ storage_path }}/s3-incoming"
        copyProduct: "false"
        filter: ""
        skipOnError: "true"
        syncOfflineProducts: ""
      - id: 6
        label: "s5"
        url: "YOUR_S5_BACKEND_URL"
        login: "{{ admin_username }}"
        password: "{{ admin_username_password }}"
        active: "true"
        page_size: "100"
        remoteIncoming: "{{ storage_path }}/s5-incoming"
        copyProduct: "false"
        filter: ""
        skipOnError: "true"
        syncOfflineProducts: ""
    datastore:
      - id: 1
        storage_name: "s1storage"
        storage_path: "{{ storage_path }}/s1-incoming"
        restriction: "referencesOnly"
        maximumSize: ""
        autoEviction: ""
      - id: 2
        storage_name: "s2a-l1cstorage"
        storage_path: "{{ storage_path }}/s2a-l1c-incoming"
        restriction: "referencesOnly"
        maximumSize: ""
        autoEviction: ""
      - id: 3
        storage_name: "s2b-l1cstorage"
        storage_path: "{{ storage_path }}/s2b-l1c-incoming"
        restriction: "referencesOnly"
        maximumSize: ""
        autoEviction: ""
      - id: 4
        storage_name: "s2-l2astorage"
        storage_path: "{{ storage_path }}/s2-l2a-incoming"
        restriction: "referencesOnly"
        maximumSize: ""
        autoEviction: ""
      - id: 5
        storage_name: "s3storage"
        storage_path: "{{ storage_path }}/s3-incoming"
        restriction: "referencesOnly"
        maximumSize: ""
        autoEviction: ""
      - id: 6
        storage_name: "s5storage"
        storage_path: "{{ storage_path }}/s5-incoming"
        restriction: "referencesOnly"
        maximumSize: ""
        autoEviction: ""
